FROM python:3.12.8

RUN apt-get install curl
RUN pip install pandas pyarrow sqlalchemy psycopg2

WORKDIR /app
COPY ingest_zones_lookup_data.py ingest_zones_lookup_data.py

ENTRYPOINT [ "python", "ingest_zones_lookup_data.py" ]